### ISSUE TITLE
Model and test frame handling

### ISSUE THREAD

**Issue by Jookia** [printers-for-people/ACEResearch#5]
Right now we have a fairly incomplete picture of how the frame handling works. Writing a simulation in Python and then a tester in C that can run on the printer and validate assumptions is a good start.

The current state machine model I'm going to assume the ACE has is:

- It discards bytes until seeing 0xFF
- It reads 0xAA
- It reads the length
- It reads length bytes and calculates the CRC
- It reads the CRC and checks it
- It reads 0xFE

If any of these fail, it will restart the entire process. The following tests should help validate this behaviour:

- Writing a stream of 0x00 through 0xFE should do nothing at all.
- Writing 0xFF then any byte except 0xAA should do nothing at all.
- Writing a 0x0000 length should have an empty payload.
- Writing a 0xFFFF length should have a full payload.
- Embedding 0xFF or 0xFE in the payload should get a response.
- Writing an invalid CRC should do nothing at all.
- Writing a non-0xFE end should do nothing at all.
- Writing a valid packet should get a response.

The test would work by sending a valid packet, then a bad packet, then a valid packet. The test succeeds if the bad packet does not influence the second response.

**Comment by wiltwong** [comment]
Probably easier to compile a serial to net proxy for the Kobra 3 and use socat on a remote computer to do this kinda testing before going to make a static binary. I'll try to compile and get binaries for https://github.com/cminyard/ser2net or something equivalent this week.

**Comment by Jookia** [comment]
After thinking through #8 , I'm genuinely curious if the input buffer is capped at 64 bytes (one CDC packet). It would be a good idea to test larger packets.

**Comment by Jookia** [comment]
I have been provided remote access to an ACE and have started poking at it with more tests today. I have some findings so far:

- Frames can be placed anywhere in a packet
- Multiple frames can be placed in a single packet
- Sending a 0xFF, 0xFE or 0xFF 0xFE does nothing
- Sending a 0xFF 0xAA 0xFE crashes the ACE
- Sending a 0xFF 0xAA 0x00 0xFE crashes the ACE
- Sending a 0xFF 0xAA 0x00 0xFE 0x00 0x00 0x00 crashes the ACE
- Sending a 0xFF 0xAA 0x00 0x00 0xFE pings sometimes
- Sending a 0xFF 0xAA 0x00 0x00 0x00 0xFE pings sometimes
- Sending a 0xFF 0xAA 0x00 0x00 0x00 0x00 0xFE always works
- Sending a 0xFF 0xAA 0x00 0x00 0x00 0x00 0x00 0x00 0xFE always works, depending on a race it may re-run the last command
- Sending a get_status with a bunch of 0x00 after the CRC works
- Sending a get_status with enough 0x00 after to require multiple CDC packets works
- Sending a get_status with an insane amount of 0x00 after doesn't work
- If the checksum contains 0xFE or 0xFF get_status works fine

When I say 'ping sometimes' I mean that it pings the keepalive only if I reconnect after sending data. Which is ... weird.

If it scanned from 0xFF 0xAA to 0xFE it would mangle the checksum, but if it scanned 0xFF, 0xAA then read a length it wouldn't find a 0xFE after the checksum and should error. Right?

Maybe the logic is that it reads the frame then discards data until 0xFE? That's certainly what it looks like. It also seems like there's some kind of buffering happening to read across packet lines, but it can get full with too many zeroes. I'll have a think about all of this.

**Comment by Jookia** [comment]
Alright, I think I know what's happening. Mostly. There's some sort of buffer for frame data that the parser writes to, and it discards data after the checksum but before the 0xFE. I've uploaded a ton of tests that validate this behaviour, including seeing that the maximum frame size is 1024 bytes.

HOWEVER, I hit a very strange situation: If you send a valid frame followed by non-frame data to the point that Linux writes 1024 bytes, it will discard the frame. I'm puzzled as to why this happens as the data is broken down in to 64 byte CDC packets, and the parser should stop buffering at at 0xFE and execute the command.

**Comment by Jookia** [comment]
Alright, this looks related to flow control: It seems like sending too much data too fast will overflow the USB packet buffer. But spacing out sends can cause received data to drop. I believe this solves the mystery of #8 too.

The next steps here are to implement this logic in the emulator, then perhaps write some tests to show this broken flow control behaviour, such as:

- How long of a frame can you send and at what speed before a command fails
- How slow do you have to send data to send a response
- What is the actual payload and frame limit

Edit: I haven't confirmed that the packets are maxing at CDC, the modem descriptor says 8 bytes per packet...

**Comment by Jookia** [comment]
I spent another day on this, and I think I've answered all the remaining questions needed to write an emulator and found some pitfalls. Sending more data than 1024 bytes too fast will lose data, and sending a frame with a length greater than 1024 bytes hangs the printer. I've added tests for these cases.

**Comment by Jookia** [comment]
Okay I finally found some time to write the frame parser emulator and finished it today. All tests pass, it is identical to real hardware. On to #6
