### ISSUE TITLE
Model and test RPC handling

### ISSUE THREAD

**Issue by Jookia** [printers-for-people/ACEResearch#6]
Much like #5 , we have no idea how RPC is actually handled. So I have to model and test it.

I'm going to work on the principle of laziness here and assume there's no internal schema or copying data between input and output.

- A frame is read
- The frame is parsed and validated as JSON
- A request must have an ID in it that is a number
- A request must have a valid method
- Some processing is done based on the method
- The response has the original ID
- The code is 0 if the request succeeded
- A msg is passed or is an empty string

I haven't seen an error in practice, but I'll assume for now that on failure a non-zero code returns and msg is "error". Tests to do:

- Send invalid JSON
- Send a request with no ID
- Send a request with no method
- Send a request with an invalid ID
- Send a request with an invalid method

Invalid ID here or invalid method here can mean negative number, float, double, string, etc- Just something that probably shouldn't be there. I'm going to assume the JSON is not copied between input and output so if we send some kind of weird ID object or method object it won't get passed to output.

**Comment by Jookia** [comment]
After finishing #5 it's now time to think about and running protocol tests. We can run a lot more because we don't have to wait for timeouts.

We want to test basically the schema and values of sending and response. For now I need to test the following things:

- Are any fields optional in the request
- What types can the fields be
- What if we add extra fields
- Does style matter? Can we add spaces?

After this issue we will have to move on to doing the same with ACE commands and ACE state, I haven't made an issue for that yet.

**Comment by Jookia** [comment]
I started on this this week. I initially tried to write some nice test macros but I get the feeling this is going to require much more complexity than that. As of today we have a 'test' for get_status. I'm at the point I need to split the test suite up in to a few more C files and add some more helpers, but I think I've found the correct approach.

**Comment by OoohPossum** [comment]
Hello @Jookia ,

first I want to thank you for the analysis and work on ACE Pro - research! As you mention "it is going to require much more complexity than that" here, I decided into writing this here and not in a separate issue.

Regarding the communication: Could the recently released Kobra 3 firmware on GitHub (if it is complete and including the code related to the ACE Pro communication which I don't know) help you in terms of the reverse engineering / packet specifications for the communication analysis?

It is available here: https://github.com/ANYCUBIC-3D/Kobra3

I recently saw the news regarding the GitHub Kobra 3 firmware released by Anycubic mentioned by another user at another project and thought that it maybe could allow a better understanding of the necessary commands and specifications, if (as example) it would be possible to modify it into sending or logging the received/transmitted ACE Pro command packets in a log file on the printer directly.

As I'm not specifically a coder, just a random idea based on hardware and linux knowledge.

**Comment by Jookia** [comment]
Thanks so much for pointing me towards that. I have had a look at it and it confirms a lot of what we already know. Unfortunately the source code is incomplete and doesn't seem to include the 'secret sauce' that describes how the ACE is actually driven.

That said, it includes what looks like a specification of the ACE API which is incredibly useful. Maybe they mistakenly uploaded it? :)

https://github.com/ANYCUBIC-3D/Kobra3/blob/main/klipper-go/docs/N033%E6%96%99%E7%9B%92%E9%80%9A%E4%BF%A1%E5%8D%8F%E8%AE%AE.md
https://github.com/ANYCUBIC-3D/Kobra3/blob/main/klipper-go/project/ace_proto.go

I'm going to look through it today and update PROTOCOL.md to include this information.

---

Back to this issue topic: I've thought more about how I've been trying to test get_status and have decided this is where the testing (almost) stops. I have a few tests for RPC to do as mentioned at the start of this issue, but this is the point where things go from unit testable to requiring Klipper integration and field testing. This is kind of a scary step but necessary.

**Comment by Jookia** [comment]
I've decided not to do tests for all the specific RPC commands given we don't have a stable API from Anycubic. Instead I tested that the RPC ID system isn't sequential so we can wrap around or re-use IDs properly. Actual RPC tests will be done when writing and testing the Klipper program as they are kind of tied to hardware as a side-effect and require manual intervention.
